In [1]:
import numpy as np

# Création de deux matrices 3x3
print("Création de deux matrices 3x3:")
matrice_A = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

matrice_B = np.array([[9, 8, 7],
                      [6, 5, 4],
                      [3, 2, 1]])

print("\nMatrice A:")
print(matrice_A)
print("\nMatrice B:")
print(matrice_B)

# Addition des matrices
somme = np.add(matrice_A, matrice_B)
print("\nSomme des matrices (A + B):")
print(somme)

# Soustraction des matrices
difference = np.subtract(matrice_A, matrice_B)
print("\nDifférence des matrices (A - B):")
print(difference)

# Quelques opérations supplémentaires intéressantes
print("\nOpérations supplémentaires:")

# Multiplication élément par élément
prod_element = np.multiply(matrice_A, matrice_B)
print("\nMultiplication élément par élément (A * B):")
print(prod_element)

# Multiplication matricielle
prod_matriciel = np.dot(matrice_A, matrice_B)
print("\nProduit matriciel (A @ B):")
print(prod_matriciel)

# Calcul de la moyenne de chaque matrice
print("\nMoyenne de la Matrice A:", np.mean(matrice_A))
print("Moyenne de la Matrice B:", np.mean(matrice_B))

# Somme des éléments de chaque ligne
print("\nSomme par ligne de la Matrice A:", np.sum(matrice_A, axis=1))
print("Somme par ligne de la Matrice B:", np.sum(matrice_B, axis=1))


Création de deux matrices 3x3:

Matrice A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrice B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Somme des matrices (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Différence des matrices (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Opérations supplémentaires:

Multiplication élément par élément (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Produit matriciel (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Moyenne de la Matrice A: 5.0
Moyenne de la Matrice B: 5.0

Somme par ligne de la Matrice A: [ 6 15 24]
Somme par ligne de la Matrice B: [24 15  6]
