In [1]:
import numpy as np

class MultiLayerPerceptron:
    def __init__(self):
        # Initialisation des poids et biais
        # Couche cachée (2 entrées -> 3 neurones)
        self.W1 = np.random.randn(2, 3) * 0.01
        self.b1 = np.zeros((1, 3))
        
        # Couche de sortie (3 neurones -> 1 sortie)
        self.W2 = np.random.randn(3, 1) * 0.01
        self.b2 = np.zeros((1, 1))
    
    def relu(self, Z):
        """Fonction d'activation ReLU"""
        return np.maximum(0, Z)
    
    def sigmoid(self, Z):
        """Fonction d'activation Sigmoid"""
        return 1 / (1 + np.exp(-Z))
    
    def forward_propagation(self, X):
        """
        Propagation avant
        X: entrées (n_samples, 2)
        """
        # Première couche (cachée)
        Z1 = np.dot(X, self.W1) + self.b1
        A1 = self.relu(Z1)
        
        # Deuxième couche (sortie)
        Z2 = np.dot(A1, self.W2) + self.b2
        A2 = self.sigmoid(Z2)
        
        return A2

# Création du modèle
mlp = MultiLayerPerceptron()

# Test avec les cas demandés
# Cas 1: Input (2, 3)
X1 = np.array([[2, 3]])
output1 = mlp.forward_propagation(X1)

# Cas 2: Input (1, 5)
X2 = np.array([[1, 5]])
output2 = mlp.forward_propagation(X2)

# Affichage des résultats
print("Architecture du réseau :")
print("- Couche d'entrée : 2 neurones")
print("- Couche cachée : 3 neurones (ReLU)")
print("- Couche de sortie : 1 neurone (Sigmoid)")
print("\nPoids de la couche cachée :")
print(mlp.W1)
print("\nBiais de la couche cachée :")
print(mlp.b1)
print("\nPoids de la couche de sortie :")
print(mlp.W2)
print("\nBiais de la couche de sortie :")
print(mlp.b2)
print("\nRésultats :")
print(f"Cas 1 (Input: [2, 3]) -> Output: {output1[0][0]:.4f}")
print(f"Cas 2 (Input: [1, 5]) -> Output: {output2[0][0]:.4f}")


Architecture du réseau :
- Couche d'entrée : 2 neurones
- Couche cachée : 3 neurones (ReLU)
- Couche de sortie : 1 neurone (Sigmoid)

Poids de la couche cachée :
[[ 0.00316884  0.02131119 -0.01609799]
 [ 0.00504199  0.02506933  0.00579578]]

Biais de la couche cachée :
[[0. 0. 0.]]

Poids de la couche de sortie :
[[-0.00040431]
 [-0.00227958]
 [-0.004871  ]]

Biais de la couche de sortie :
[[0.]]

Résultats :
Cas 1 (Input: [2, 3]) -> Output: 0.4999
Cas 2 (Input: [1, 5]) -> Output: 0.4999
