In [1]:
import numpy as np

# 1. Tableau 1D des températures de la semaine
# Utilisons des températures réalistes pour Paris en février
temperatures = np.array([8, 7, 9, 6, 8, 7, 9])  # en degrés Celsius
print("Températures de la semaine:")
print(temperatures)
print("Shape:", temperatures.shape)
print("\n")

# 2. Tableau 2D de forme (2,5) avec des valeurs entre 1 et 10
matrice_2d = np.array([[1, 4, 7, 3, 9],
                       [2, 5, 8, 6, 10]])
print("Matrice 2D (2 lignes, 5 colonnes):")
print(matrice_2d)
print("Shape:", matrice_2d.shape)
print("\n")

# 3. Tableau 3D pour une image de 9 pixels (3x3)
# Chaque pixel aura 3 valeurs RGB (Rouge, Vert, Bleu)
# Les valeurs RGB vont de 0 à 255
image_3d = np.array([
    # Première ligne de pixels
    [[255, 0, 0],    # Rouge
     [0, 255, 0],    # Vert
     [0, 0, 255]],   # Bleu
    
    # Deuxième ligne de pixels
    [[255, 255, 0],  # Jaune
     [255, 0, 255],  # Magenta
     [0, 255, 255]], # Cyan
    
    # Troisième ligne de pixels
    [[128, 128, 128],# Gris
     [0, 0, 0],      # Noir
     [255, 255, 255]]# Blanc
])

print("Image 3D (3x3 pixels avec valeurs RGB):")
print(image_3d)
print("Shape:", image_3d.shape)


Températures de la semaine:
[8 7 9 6 8 7 9]
Shape: (7,)


Matrice 2D (2 lignes, 5 colonnes):
[[ 1  4  7  3  9]
 [ 2  5  8  6 10]]
Shape: (2, 5)


Image 3D (3x3 pixels avec valeurs RGB):
[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [255   0 255]
  [  0 255 255]]

 [[128 128 128]
  [  0   0   0]
  [255 255 255]]]
Shape: (3, 3, 3)
