In [1]:
import numpy as np

# 1. Modification d'éléments spécifiques
print("1. Modification d'éléments spécifiques:")
array1 = np.arange(1, 11)  # Crée un tableau de 1 à 10
print("Avant:", array1)
array1[4] = 50  # Modifie le 5ème élément (index 4)
print("Après:", array1)
print("\n")

# 2. Découpage et modification d'une plage
print("2. Découpage et modification d'une plage:")
array2 = np.arange(1, 11)
print("Avant:", array2)
array2[3:8] = -array2[3:8]  # Rend négatifs les éléments de l'index 3 à 7
print("Après:", array2)
print("\n")

# 3. Modification conditionnelle avec indexation booléenne
print("3. Modification conditionnelle:")
array3 = np.random.randint(1, 101, 20)  # 20 nombres aléatoires entre 1 et 100
print("Avant:", array3)
array3[array3 > 50] = -1  # Remplace les valeurs > 50 par -1
print("Après:", array3)
print("\n")

# 4. Modification avec indexation avancée (matrice 2D)
print("4. Modification de la diagonale d'une matrice:")
array4 = np.arange(1, 26).reshape(5, 5)  # Matrice 5x5
print("Avant:")
print(array4)
np.fill_diagonal(array4, array4.diagonal() * 2)  # Double les éléments de la diagonale
print("Après:")
print(array4)
print("\n")

# 5. Impact du découpage
print("5. Impact du découpage sur le tableau original:")
array5 = np.arange(1, 11)
print("Tableau original:", array5)
slice_array = array5[2:6]  # Crée une vue du tableau
print("Tranche extraite:", slice_array)
slice_array[0] = 100  # Modifie le premier élément de la tranche
print("Tableau original après modification de la tranche:", array5)


1. Modification d'éléments spécifiques:
Avant: [ 1  2  3  4  5  6  7  8  9 10]
Après: [ 1  2  3  4 50  6  7  8  9 10]


2. Découpage et modification d'une plage:
Avant: [ 1  2  3  4  5  6  7  8  9 10]
Après: [ 1  2  3 -4 -5 -6 -7 -8  9 10]


3. Modification conditionnelle:
Avant: [89 34 52 96 59  9  9 77 66 51 60 26 41 53 28 17 78 22 56 92]
Après: [-1 34 -1 -1 -1  9  9 -1 -1 -1 -1 26 41 -1 28 17 -1 22 -1 -1]


4. Modification de la diagonale d'une matrice:
Avant:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Après:
[[ 2  2  3  4  5]
 [ 6 14  8  9 10]
 [11 12 26 14 15]
 [16 17 18 38 20]
 [21 22 23 24 50]]


5. Impact du découpage sur le tableau original:
Tableau original: [ 1  2  3  4  5  6  7  8  9 10]
Tranche extraite: [3 4 5 6]
Tableau original après modification de la tranche: [  1   2 100   4   5   6   7   8   9  10]
