In [1]:
import numpy as np

# 1. Remodelage d'un tableau
print("1. REMODELAGE D'UN TABLEAU")
# Création d'un tableau 1D avec 12 éléments
array_1d = np.arange(1, 13)  # Crée un tableau de 1 à 12
print("Tableau original 1D:", array_1d)

# Remodelage en matrice 4x3
matrix_4x3 = array_1d.reshape(4, 3)
print("\nRemodelé en 4x3:")
print(matrix_4x3)

# Remodelage en matrice 2x6
matrix_2x6 = array_1d.reshape(2, 6)
print("\nRemodelé en 2x6:")
print(matrix_2x6)
print("\n")

# 2. Transposition de matrice
print("2. TRANSPOSITION DE MATRICE")
# Transposition de la matrice 2x6
transposed_2x6 = matrix_2x6.T
print("Matrice 2x6 originale:")
print(matrix_2x6)
print("\nMatrice transposée (6x2):")
print(transposed_2x6)
print("\n")

# 3. Combinaison de remodelage et transposition
print("3. COMBINAISON DE REMODELAGE ET TRANSPOSITION")
# Création d'une matrice 3x4
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("Matrice 3x4 originale:")
print(matrix_3x4)

# Transposition
transposed_3x4 = matrix_3x4.T
print("\nMatrice transposée (4x3):")
print(transposed_3x4)

# Remodelage en tableau 1D
final_1d = transposed_3x4.reshape(-1)  # -1 signifie "calculer automatiquement cette dimension"
print("\nRemodelé en 1D:")
print(final_1d)


1. REMODELAGE D'UN TABLEAU
Tableau original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Remodelé en 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Remodelé en 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


2. TRANSPOSITION DE MATRICE
Matrice 2x6 originale:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Matrice transposée (6x2):
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


3. COMBINAISON DE REMODELAGE ET TRANSPOSITION
Matrice 3x4 originale:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrice transposée (4x3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Remodelé en 1D:
[ 1  5  9  2  6 10  3  7 11  4  8 12]
