EXERCICE 1

In [1]:
import numpy as np

# Création d'un tableau de 0 à 9
tableau = np.arange(10)  # arange crée un tableau de 0 jusqu'à (mais n'incluant pas) 10

print("Tableau créé :")
print(tableau)


Tableau créé :
[0 1 2 3 4 5 6 7 8 9]


EXERCICE 2

In [ ]:
# 1. Création de la liste initiale avec des nombres flottants
liste_originale = [3.14, 2.17, 0, 1, 2]
print("Liste originale :", liste_originale)

# 2. Conversion en tableau NumPy et changement de type en entier
tableau = np.array(liste_originale, dtype=int)
print("\nTableau NumPy converti en entiers :")
print(tableau)


Liste originale : [3.14, 2.17, 0, 1, 2]

Tableau NumPy converti en entiers :
[3 2 0 1 2]


EXERCICE 3

In [10]:
# Création d'un tableau 3x3 avec les valeurs de 1 à 9
tableau = np.arange(1, 10).reshape(3, 3)

print("Tableau 3x3 :")
print(tableau)


Tableau 3x3 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
EXERCICE 4

In [ ]:
# Exercice 4 : Tableau 2D avec nombres aléatoires
np.random.seed(42)  # Pour la reproductibilité
tableau_aleatoire = np.random.random((4, 5))

# Arrondir à 2 décimales
tableau_arrondi = np.round(tableau_aleatoire, decimals=2)

print(tableau_arrondi)


[[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]]


In [ ]:
EXERCICE 5

In [ ]:
# Exercice 5 : Indexation de tableaux
array = np.array([[21,22,23,22,22],
                 [20,21,22,23,24],
                 [21,22,23,22,22]])
deuxieme_ligne = array[1]
print(deuxieme_ligne)
print("\n")

[20 21 22 23 24]




In [ ]:
EXERCICE 6

In [ ]:
# Exercice 6 : Inversion des éléments
tableau = np.arange(10)
tableau_inverse = tableau[::-1]
print(tableau_inverse)
print("\n")

[9 8 7 6 5 4 3 2 1 0]




In [ ]:
EXERCICE 7

In [ ]:
# Exercice 7 : Matrice identité
matrice_identite = np.eye(4)
print(matrice_identite)
print("\n")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]




EXERCICE 8

In [ ]:
# Exercice 8 : Fonctions d'agrégation simples
tableau = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
somme = np.sum(tableau)
moyenne = np.mean(tableau)
print(f"Somme: {somme}, Moyenne: {moyenne}")
print("\n")

Somme: 45, Moyenne: 4.5




EXERCICE 9

In [ ]:
# Exercice 9 : Création et restructuration de tableau
tableau = np.arange(1, 21).reshape(4, 5)
print(tableau)
print("\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]




In [ ]:
EXERCICE 10

In [ ]:
# Exercice 10 : Sélection conditionnelle
tableau = np.arange(10)
nombres_impairs = tableau[tableau % 2 == 1]
print(nombres_impairs)

[1 3 5 7 9]
